// app/(marketing)/legal/privacy/page.tsx
import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Privacy Policy',
};

export default function PrivacyPolicyPage() {
  return (
    <div className="container py-20">
      <div className="mx-auto max-w-2xl prose prose-neutral">
        <h1 className="font-display">Privacy Policy</h1>
        <p className="text-sm text-muted-foreground">Last updated: January 2026</p>

        <h2>What we collect</h2>
        <p>
          We collect the information you provide when creating a profile (name, photo, contact
          details, bio, links), information generated by using the product (analytics events like
          scans and taps, leads submitted through your profile), and standard account information
          (email address, via passwordless sign-in).
        </p>

        <h2>How we use it</h2>
        <p>
          We use your information to operate your public profile, provide analytics on how it is
          used, process card orders and subscriptions, and communicate with you about your
          account, orders, and (if you opt in) product updates.
        </p>

        <h2>What visitors to your profile see</h2>
        <p>
          Only the fields you choose to publish are visible on your public profile page. Contact
          information you do not add is never shown. Lead form submissions are private to you (and
          your organization&apos;s admins, if your card was issued by an organization).
        </p>

        <h2>Data retention</h2>
        <p>
          Raw analytics events are retained for 90 days and rolled into daily aggregates
          thereafter. Billing and order records are retained as required for accounting and legal
          compliance. Deleting your account unpublishes your profile immediately; contact support
          for full data erasure requests.
        </p>

        <h2>Organization-issued cards</h2>
        <p>
          If your card was issued by an employer or organization, analytics and lead data
          generated through that card belong to the organization, as disclosed in the
          organization&apos;s agreement with Connect Cards.
        </p>

        <h2>Contact</h2>
        <p>
          Questions about this policy can be sent through our{' '}
          <Link href="/contact">contact page</Link>.
        </p>
      </div>
    </div>
  );
}
